server:
  port: 8099

spring:
  mail:
    host: smtp.qq.com
    post: 465
    username:
    password:
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mail:
  subject: WARNING
  #当前邮箱
  from:
  #目标邮箱
  to:

app:
  urls: http://192.168.5.182:8088/agent

JohnYehyo:
  version: 1.0.0